# Generated by Django 5.2.4 on 2025-08-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=50)),
                ("employer", models.CharField(max_length=150)),
                ("duties", models.TextField()),
                ("updated", models.DateTimeField(auto_now_add=True)),
                ("picture", models.ImageField(blank=True, upload_to="")),
                ("slug", models.SlugField()),
            ],
        ),
    ]
