# Generated by Django 5.2.4 on 2025-09-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=150)),
                ("project_img", models.ImageField(blank=True, upload_to="")),
                ("Project_desc", models.TextField()),
                ("date_completed", models.DateField()),
            ],
        ),
    ]
