# Generated by Django 5.2.5 on 2025-09-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="project_slug",
            field=models.SlugField(default="abcdef"),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_url",
            field=models.URLField(default="Enter URL here"),
        ),
    ]
